version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs-app
    restart: unless-stopped
    expose:
      - "3000"  # Expose internally to the network, no need to expose publicly!
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true