services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
    expose:
      - "3001"
    restart: unless-stopped
    networks:
      - caddy_net

volumes:
  uptime-kuma-data:

networks:
  caddy_net:
    external: true
