import { coreConnection } from '../config/db.js';
import mongoose from 'mongoose';

const groupSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, 'Group name is required'],
      trim: true,
    },
    coachingCode: {
      type: String,
      uppercase: true,
      trim: true,
      default: null, // null for B2C groups
    },
    tenantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Tenant',
      required: true,
      index: true,
    },
    members: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
      },
    ],
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    isAutoGenerated: {
      type: Boolean,
      default: false, // true = auto-created on CSV bulk upload
    },
    description: {
      type: String,
      trim: true,
      default: '',
    },
  },
  { timestamps: true }
);

// Compound index for fast tenant-scoped group lookups
groupSchema.index({ tenantId: 1, name: 1 });
// Index for fast "which groups is this user in?" queries
groupSchema.index({ members: 1 });

const Group = coreConnection.model('Group', groupSchema);
export default Group;
